ci: don't require Changelog entries for merge commits
Changelog-Changed: ci: don't require Changelog entries for merge commits

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -160,10 +160,15 @@ changelog:
   before_script:
     - git fetch origin main:main
   script:
-    - >
-      if git log 'main..HEAD' --pretty="%s%x09%b" | grep -q -E 'Changelog-(\S*): (.*)$'; then
-        echo "Changelog commit message found.";
+    - |
+      if [ "$(git cat-file -p $CI_COMMIT_SHA | grep -c 'parent')" -gt 1 ]; then
+        echo "This is a merge commit, don't require a changelog entry"
       else
-        echo "Error: No Changelog commit message found.";
-        exit 1;
+        echo "This is not a merge commit."
+        if git log 'main..HEAD' --pretty="%s%x09%b" | grep -q -E 'Changelog-(\S*): (.*)$'; then
+          echo "Changelog commit message found.";
+        else
+          echo "Error: No Changelog commit message found.";
+          exit 1;
+        fi
       fi
